### ISSUE TITLE
Create .gitignore

### ISSUE THREAD

**Issue by adriancast** [adriancast/spotify-roulette#16]
The repository does not contain any .gitignore, we should add one with all the IDE files at least

**Comment by SubhrajitPrusty** [comment]
but there is one [.gitignore](https://github.com/adriancast/spotify-roulette/blob/master/.gitignore)

**Comment by adriancast** [comment]
My bad @SubhrajitPrusty , there was a .vscode folder in the repo that was created before the .gitignore file. I did not notice there is a .gitignore file with the proper settings until I create the task.
Sorry again, cheers
